services:
  - type: web
    name: nexos
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    disk:
      name: nexos-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: VOICE_CHANNEL_ID
        sync: false
      - key: MEMBER_COUNT_CHANNEL_ID
        value: 1511798754980663492
      - key: LOG_CHANNEL_ID
        sync: false
      - key: YOUTUBE_COOKIES
        sync: false
      - key: YOUTUBE_COOKIES_FILE
        sync: false
      - key: NEXOS_DATA_DIR
        value: /var/data/nexos
